---
# Role tasks
- set_fact:
    config_file: "/etc/sysctl.conf"

- name: backup config file
  become: true
  shell: "cp {{ config_file }} {{ config_file }}.`date +%Y%m%d%H%M%S`"
  changed_when: false

- name: configure systctl.conf
  ## become: true
  sysctl:
    name: "{{ item.value.option_name }}"
    value: "{{ item.value.option_value }}"
    state: "{{ item.value.option_status }}"
    reload: no
    sysctl_set: yes
  with_dict: "{{ sysctl_options_list }}"
  when: sysctl_options_list is defined
  register: status

- name: reload sysctl.conf
  shell: "sysctl -p"
  changed_when: false
  when: sysctl_reload_config and (status | changed)
