---
# Role tasks
- include: backup_sysctl.yml

- name: configure sysctl.conf
  become: true
  sysctl:
    name: "{{ item.value.option_name }}"
    value: "{{ item.value.option_value }}"
    state: "{{ item.value.option_status }}"
    sysctl_file: "{{ sysctl_file }}"
    reload: no
    sysctl_set: yes
  with_dict: "{{ sysctl_options_list }}"
  when: sysctl_options_list is defined
  register: status

- name: remove line from sysctl file
  lineinfile:
    path: "{{ sysctl_file }}"
    line: "{{ item.value.option_name }} = {{ item.value.option_value }}"
    state: absent
  when: item.value.option_status == 'absent'
  with_dict: "{{ sysctl_options_list }}"

- name: reload sysctl.conf
  become: true
  shell: "sysctl -p {{ sysctl_file }}"
  changed_when: false
  when: sysctl_reload_config and (status is changed)
