---
# Role tasks

- block:
    - name: Configure sysctl
      sysctl:
        ignoreerrors: "{{ sysctl_item.1.ignoreerrors | default(omit) }}"
        name: "{{ sysctl_item.1.name }}"
        reload: "{{ sysctl_item.1.reload | default(omit) }}"
        state: "{{ sysctl_item.1.state | default(omit) }}"
        sysctl_file: "{{ sysctl_item.0.path | default(omit) }}"
        sysctl_set: "{{ sysctl_item.1.sysctl_set | default(omit) }}"
        value: "{{ item.value.option_value }}"
      loop: "{{ sysctl_to_manage | subelements('options') }}"
      loop_control:
        loop_var: sysctl_item
        label: "{{ sysctl_item.name }}"
  vars:
    sysctl_to_manage: >-
      {{ sysctl
         + ((sysctl_load_from_hostvars)
            | ternary(sysctl_hostvars | default([]) | flatten, [])) }}
  tags:
    - role::sysctl
